version: 2.1
default_test_steps: &default_test_steps
  steps:
    - checkout
    - run: yarn
    - run: pip install -r ./requirements.txt --user
    - run: yarn percy exec -- python ./tests.py

jobs:
  test_python_2:
    docker:
      - image: circleci/python:2-node-browsers
    <<: *default_test_steps
  test_python_3:
    docker:
      - image: circleci/python:3-node-browsers
    <<: *default_test_steps

workflows:
  version: 2.1
  test:
    jobs:
      - test_python_2
      - test_python_3
